/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.dbd.colegio.view.frame;

import co.edu.usbbog.dbd.colegio.controller.logic.AcudienteBO;
import co.edu.usbbog.dbd.colegio.controller.logic.DocenteBO;
import co.edu.usbbog.dbd.colegio.controller.logic.EstudianteBO;
import co.edu.usbbog.dbd.colegio.model.AcudienteDTO;
import co.edu.usbbog.dbd.colegio.model.DocenteDTO;
import co.edu.usbbog.dbd.colegio.model.EstudianteDTO;
import co.edu.usbbog.dbd.colegio.view.window.AcudienteJPanel;
import co.edu.usbbog.dbd.colegio.view.window.DocenteJPanel;
import co.edu.usbbog.dbd.colegio.view.window.EstudianteJPanel;
import java.util.List;

/**
 *
 * @author diego
 */
public class ColegioJFrame extends javax.swing.JFrame {
    private AcudienteJPanel acudienteJPanel;
    private DocenteJPanel docenteJPanel;
    private EstudianteJPanel estudianteJPanel;
    
    private AcudienteBO abo;
    private DocenteBO dbo;
    private EstudianteBO ebo;
    
    /** Creates new form ColegioJFrame */
    public ColegioJFrame() {
        this.setTitle("Colegio");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.comenzar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColegioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColegioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColegioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColegioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColegioJFrame().setVisible(true);
            }
        });
    }

    public AcudienteJPanel getAcudienteJPanel() {
        return acudienteJPanel;
    }

    public DocenteJPanel getDocenteJPanel() {
        return docenteJPanel;
    }

    public EstudianteJPanel getEstudianteJPanel() {
        return estudianteJPanel;
    }

    public AcudienteBO getAbo() {
        return abo;
    }

    public DocenteBO getDbo() {
        return dbo;
    }

    public EstudianteBO getEbo() {
        return ebo;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    //--------------------------------------------------------------------------
    //METODOS DE NAVEGACIÓN:
    
    //Iniciar App
    private void comenzar() {
        this.estudianteJPanel = new EstudianteJPanel(this);
        this.estudianteJPanel.setVisible(true);
        this.add(this.estudianteJPanel);
        this.pack();
        this.setLocationRelativeTo(null);
    }
    
    //Navegación por ventanas
    //Acudiente
    public void IrDeAcudienteADocente() {
        this.remove(this.acudienteJPanel);
        this.acudienteJPanel = null;
        this.docenteJPanel = new DocenteJPanel(this);
        this.docenteJPanel.setVisible(true);
        this.add(this.docenteJPanel);
        this.pack();
        this.setLocationRelativeTo(null);
        this.acudienteJPanel = null;
    }
    
    public void IrDeAcudienteAEstudiante() {
        this.remove(this.acudienteJPanel);
        this.acudienteJPanel = null;
        this.estudianteJPanel = new EstudianteJPanel(this);
        this.estudianteJPanel.setVisible(true);
        this.add(this.estudianteJPanel);
        this.pack();
        this.setLocationRelativeTo(null);
        this.acudienteJPanel = null;
    }
    
    //Docente
    public void IrDeDocenteAAcudiente() {
        this.remove(this.docenteJPanel);
        this.docenteJPanel = null;
        this.acudienteJPanel = new AcudienteJPanel(this);
        this.acudienteJPanel.setVisible(true);
        this.add(this.acudienteJPanel);
        this.pack();
        this.setLocationRelativeTo(null);
        this.docenteJPanel = null;
    }
    
    public void IrDeDocenteAEstudiante() {
        this.remove(this.docenteJPanel);
        this.docenteJPanel = null;
        this.estudianteJPanel = new EstudianteJPanel(this);
        this.estudianteJPanel.setVisible(true);
        this.add(this.estudianteJPanel);
        this.pack();
        this.setLocationRelativeTo(null);
        this.docenteJPanel = null;
    }
    
    //Estudiante
    public void IrDeEstudianteAAcudiente() {
        this.remove(this.estudianteJPanel);
        this.estudianteJPanel = null;
        this.acudienteJPanel = new AcudienteJPanel(this);
        this.acudienteJPanel.setVisible(true);
        this.add(this.acudienteJPanel);
        this.pack();
        this.setLocationRelativeTo(null);
        this.estudianteJPanel = null;
    }
    
    public void IrDeEstudianteADocente() {
        this.remove(this.estudianteJPanel);
        this.estudianteJPanel = null;
        this.docenteJPanel = new DocenteJPanel(this);
        this.docenteJPanel.setVisible(true);
        this.add(this.docenteJPanel);
        this.pack();
        this.setLocationRelativeTo(null);
        this.estudianteJPanel = null;
    }
    
    //--------------------------------------------------------------------------
    //MÉTODOS LÓGICOS:
    
    //Llamado de datos
    public List<AcudienteDTO> mostrarA() {
        this.abo = new AcudienteBO();
        return this.abo.mostrarA();
    }

    public List<DocenteDTO> mostrarD() {
        this.dbo = new DocenteBO();
        return this.dbo.mostrarD();
    }

    public List<EstudianteDTO> mostrarE() {
        this.ebo = new EstudianteBO();
        return this.ebo.mostrarE();
    }
    
    //Acudiente
    public String crearAcudiente(Integer id_acu, Integer estudiante_id_est, String nombre, String apellido, String tipo, Integer telefono) {
        this.abo = new AcudienteBO();
        return this.abo.crearAcudiente(id_acu, nombre, apellido, tipo, telefono, estudiante_id_est);
    }

    public String buscarAcudiente(int id_acu) {
        this.abo = new AcudienteBO();
        return this.abo.buscarAcudiente(id_acu);
    }

    public String actualizarAcudiente(Integer id_acu, Integer estudiante_id_est, String nombre, String apellido, String tipo, Integer telefono) {
        this.abo = new AcudienteBO();
        return this.abo.actualizarAcudiente(id_acu, nombre, apellido, tipo, telefono, estudiante_id_est);
    }

    public String eliminarAcudiente(int id_acu) {
        this.abo = new AcudienteBO();
        return this.abo.eliminarAcudiente(id_acu);
    }
    
    //Docente
    public String crearDocente(Integer id_doc, Integer estudiante_id_est, String nombre, String apellido, Integer edad, String curso) {
        this.dbo = new DocenteBO();
        return this.dbo.crearDocente(id_doc, estudiante_id_est, nombre, apellido, edad, curso);
    }

    public String buscarDocente(int id_doc) {
        this.dbo = new DocenteBO();
        return this.dbo.buscarDocente(id_doc);
    }

    public String actualizarDocente(Integer id_doc, Integer estudiante_id_est, String nombre, String apellido, Integer edad, String curso) {
        this.dbo = new DocenteBO();
        return this.dbo.actualizarDocente(id_doc, estudiante_id_est, nombre, apellido, edad, curso);
    }

    public String eliminarDocente(int id_doc) {
        this.dbo = new DocenteBO();
        return this.dbo.eliminarDocente(id_doc);
    }
    
    //Estudiante
    public String crearEstudiante(Integer id_est, String nombre, String apellido, Integer edad, String grado) {
        this.ebo = new EstudianteBO();
        return this.ebo.crearEstudiante(id_est, nombre, apellido, edad, grado);
    }

    public String buscarEstudiante(int id_est) {
        this.ebo = new EstudianteBO();
        return this.ebo.buscarEstudiante(id_est);
    }

    public String actualizarEstudiante(Integer id_est, String nombre, String apellido, Integer edad, String grado) {
        this.ebo = new EstudianteBO();
        return this.ebo.actualizarEstudiante(id_est, nombre, apellido, edad, grado);
    }

    public String eliminarEstudiante(int id_est) {
        this.ebo = new EstudianteBO();
        return this.ebo.eliminarEstudiante(id_est);
    }
}
