/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.dbd.colegio.view.window;

import co.edu.usbbog.dbd.colegio.model.EstudianteDTO;
import co.edu.usbbog.dbd.colegio.view.frame.ColegioJFrame;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class EstudianteJPanel extends javax.swing.JPanel {
    private ColegioJFrame appJframe;
    /**
     * Creates new form EstudianteJPanel
     */
    public EstudianteJPanel(ColegioJFrame appJframe) {
        this.appJframe = appJframe;
        initComponents();
        this.mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResgristosA = new javax.swing.JScrollPane();
        RegistrosE = new javax.swing.JTextArea();
        CerrarE = new javax.swing.JButton();
        Ir_AcudienteE = new javax.swing.JButton();
        Ir_DocenteE = new javax.swing.JButton();
        EliminarE = new javax.swing.JButton();
        ActualizarE = new javax.swing.JButton();
        BuscarE = new javax.swing.JButton();
        CrearE = new javax.swing.JButton();
        Grado_TextE = new javax.swing.JTextField();
        Edad_TextE = new javax.swing.JTextField();
        Apellido_TextE = new javax.swing.JTextField();
        Nombre_TextE = new javax.swing.JTextField();
        ID_TextE = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        Subtitulo = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Separador_2 = new javax.swing.JSeparator();
        Separador_1 = new javax.swing.JSeparator();
        FondoE = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistrosE.setEditable(false);
        RegistrosE.setColumns(20);
        RegistrosE.setRows(5);
        ResgristosA.setViewportView(RegistrosE);

        add(ResgristosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 530, 110));

        CerrarE.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        CerrarE.setForeground(new java.awt.Color(255, 0, 0));
        CerrarE.setText("Cerrar");
        CerrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarEActionPerformed(evt);
            }
        });
        add(CerrarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 120, -1));

        Ir_AcudienteE.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        Ir_AcudienteE.setForeground(new java.awt.Color(255, 255, 0));
        Ir_AcudienteE.setText("Ir a Acudiente");
        Ir_AcudienteE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ir_AcudienteEActionPerformed(evt);
            }
        });
        add(Ir_AcudienteE, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 120, -1));

        Ir_DocenteE.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        Ir_DocenteE.setForeground(new java.awt.Color(255, 255, 0));
        Ir_DocenteE.setText("Ir a Docente");
        Ir_DocenteE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ir_DocenteEActionPerformed(evt);
            }
        });
        add(Ir_DocenteE, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 120, -1));

        EliminarE.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        EliminarE.setForeground(new java.awt.Color(255, 255, 0));
        EliminarE.setText("Eliminar");
        EliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEActionPerformed(evt);
            }
        });
        add(EliminarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 90, -1));

        ActualizarE.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        ActualizarE.setForeground(new java.awt.Color(255, 255, 0));
        ActualizarE.setText("Actualizar");
        ActualizarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarEActionPerformed(evt);
            }
        });
        add(ActualizarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 90, -1));

        BuscarE.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        BuscarE.setForeground(new java.awt.Color(255, 255, 0));
        BuscarE.setText("Buscar");
        BuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarEActionPerformed(evt);
            }
        });
        add(BuscarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 90, -1));

        CrearE.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        CrearE.setForeground(new java.awt.Color(255, 255, 0));
        CrearE.setText("Crear");
        CrearE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEActionPerformed(evt);
            }
        });
        add(CrearE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 90, -1));
        add(Grado_TextE, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 180, -1));
        add(Edad_TextE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 180, -1));
        add(Apellido_TextE, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 180, -1));
        add(Nombre_TextE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 180, -1));
        add(ID_TextE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, -1));

        Telefono.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        Telefono.setForeground(new java.awt.Color(255, 255, 0));
        Telefono.setText("Grado:");
        add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        Tipo.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        Tipo.setForeground(new java.awt.Color(255, 255, 0));
        Tipo.setText("Edad:");
        add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        Apellido.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        Apellido.setForeground(new java.awt.Color(255, 255, 0));
        Apellido.setText("Apellido:");
        add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        Nombre.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 0));
        Nombre.setText("Nombre:");
        add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        ID.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 0));
        ID.setText("ID:");
        add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 30, -1));

        Subtitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Subtitulo.setForeground(new java.awt.Color(255, 255, 0));
        Subtitulo.setText("Estudiantes Registrados:");
        add(Subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        Titulo.setBackground(new java.awt.Color(0, 0, 0));
        Titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 0));
        Titulo.setText("Estudiante");
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 30));

        Separador_2.setForeground(new java.awt.Color(255, 255, 0));
        add(Separador_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 730, -1));

        Separador_1.setForeground(new java.awt.Color(255, 255, 0));
        add(Separador_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 730, 10));

        FondoE.setBackground(new java.awt.Color(255, 0, 51));
        add(FondoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void CrearEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEActionPerformed
        this.create();
    }//GEN-LAST:event_CrearEActionPerformed

    private void BuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarEActionPerformed
        this.read(); 
    }//GEN-LAST:event_BuscarEActionPerformed

    private void ActualizarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarEActionPerformed
        this.update();
    }//GEN-LAST:event_ActualizarEActionPerformed

    private void EliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEActionPerformed
        this.delete();
    }//GEN-LAST:event_EliminarEActionPerformed

    private void Ir_DocenteEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ir_DocenteEActionPerformed
        this.appJframe.IrDeEstudianteADocente();
    }//GEN-LAST:event_Ir_DocenteEActionPerformed

    private void Ir_AcudienteEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ir_AcudienteEActionPerformed
        this.appJframe.IrDeEstudianteAAcudiente();
    }//GEN-LAST:event_Ir_AcudienteEActionPerformed

    private void CerrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarEActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CerrarEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarE;
    private javax.swing.JLabel Apellido;
    private javax.swing.JTextField Apellido_TextE;
    private javax.swing.JButton BuscarE;
    private javax.swing.JButton CerrarE;
    private javax.swing.JButton CrearE;
    private javax.swing.JTextField Edad_TextE;
    private javax.swing.JButton EliminarE;
    private javax.swing.JPanel FondoE;
    private javax.swing.JTextField Grado_TextE;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField ID_TextE;
    private javax.swing.JButton Ir_AcudienteE;
    private javax.swing.JButton Ir_DocenteE;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField Nombre_TextE;
    private javax.swing.JTextArea RegistrosE;
    private javax.swing.JScrollPane ResgristosA;
    private javax.swing.JSeparator Separador_1;
    private javax.swing.JSeparator Separador_2;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatos() {
        RegistrosE.setText("");
        List<EstudianteDTO> estudiantes = this.appJframe.mostrarE();
        for (EstudianteDTO estudiante : estudiantes) {
            RegistrosE.append(estudiante.toString() + "\n");
        }
    }
    
    private boolean validarD() {
        if (ID_TextE.getText().equals("")) {
            return false;
        } else if (Nombre_TextE.getText().equals("")) {
            return false;
        } else if (Apellido_TextE.getText().equals("")) {
            return false;
        } else if (Edad_TextE.getText().equals("")) {
            return false;
        } else if (Grado_TextE.getText().equals("")) {
            return false;
        }else {
            try {
                int id = Integer.parseInt(ID_TextE.getText());
                int edad = Integer.parseInt(Edad_TextE.getText());

                return true;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error en el ingreso de datos");
                return false;
            }
        }
    }
    
    private void clean() {
        ID_TextE.setText("");
        Nombre_TextE.setText("");
        Apellido_TextE.setText("");
        Edad_TextE.setText("");
        Grado_TextE.setText("");
    }
    
    private void create() {
        if (this.validarD()) {
            String salida = this.appJframe.crearEstudiante(Integer.parseInt(ID_TextE.getText()),
                    Nombre_TextE.getText(),
                    Apellido_TextE.getText(),
                    Integer.parseInt(Edad_TextE.getText()),
                    Grado_TextE.getText());
             JOptionPane.showMessageDialog(this, salida);
             this.clean();
        } else {
            System.out.println("Error");
            JOptionPane.showMessageDialog(this, "Por favor, inserte los datos");
        }
    }
    
    private void read() {
        try {
            String ask = this.appJframe.buscarEstudiante(Integer.parseInt(ID_TextE.getText()));
             JOptionPane.showMessageDialog(null, ask);
             this.clean();
        } catch (Exception e) {
            System.out.println("Error");
            JOptionPane.showMessageDialog(this, "Dato Erroneo");
        }
    }
    
    private void update() {
        if (this.validarD()) {
            String salida = this.appJframe.crearEstudiante(Integer.parseInt(ID_TextE.getText()),
                    Nombre_TextE.getText(),
                    Apellido_TextE.getText(),
                    Integer.parseInt(Edad_TextE.getText()),
                    Grado_TextE.getText());
             JOptionPane.showMessageDialog(this, salida);
             this.clean();
        } else {
            System.out.println("Error");
            JOptionPane.showMessageDialog(this, "Por favor, inserte los datos");
        }
    }
    
    private void delete() {
        try {
            String ask = this.appJframe.eliminarEstudiante(Integer.parseInt(ID_TextE.getText()));
            JOptionPane.showMessageDialog(null,"ID eliminado: " + ask);
            this.clean();
        } catch (Exception e) {
            System.out.println("Error");
            JOptionPane.showMessageDialog(this, "Dato Erroneo");
        }
    }
}
